### ISSUE TITLE
How can I add h5p button to TinyMCE editor in CodeIgniter Project

### ISSUE THREAD

**Issue by hassankhattak58** [catalyst/moodle-tinymce_h5p#7]
Hi,
I am stuck at the point of adding h5p interactive components to a Code Igniter (PHP) course website. 
There is a TinyMCE Editor there, Now How can I add an h5p button so that I can add an interactive component?

Thanks.

**Comment by hassankhattak58** [comment]
I think should add a button to tinyMCE editor on-click will open a model having a form, where we can upload our downloaded .h5p content and with a library it will do like explained here [h5p.org/creating-your-own-h5p-plugin](https://h5p.org/creating-your-own-h5p-plugin) in Uploading H5P Files section. What do you think it will work? I need advice. Thanks

**Comment by ScottVerbeek** [comment]
Hi @hassankhattak58, this software is written specifically for the Moodle LMS platform. I will not work with Code Igniter. Hope this helps. Cheers, Scott.
